services:
  frontend:
    image: bibi1211/ccc-fe:v1.0
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://103.179.175.95:8000"
      VITE_WEBHOOK_UPLOAD_URL: "https://iconic-host.lapage.vn/webhook/upload-file"
      VITE_WEBHOOK_CHUNKING_URL: "https://iconic-host.lapage.vn/webhook/chunking"
    restart: unless-stopped
